apiVersion: apps/v1
kind: Deployment
metadata:
    name: server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                - name: server
                  image: server:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 5000
                  env:
                      - name: MONGODB_URI
                        value: "mongodb://mongodb:27017/chatapp"
                      - name: REDIS_URL
                        value: "redis://redis:6379"
---
apiVersion: v1
kind: Service
metadata:
    name: server
spec:
    type: NodePort
    selector:
        app: server
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
          nodePort: 30002
